"""Hermes cron integration helpers for LifeEngine heartbeat.

The plugin remains embedded: this module writes a script into ~/.hermes/scripts/
that imports the local plugin package and runs a no-agent heartbeat tick. Hermes'
cron can then run that script with --no-agent.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

from .jsonutil import dumps
from .paths import hermes_home

SCRIPT_NAME = "lifeengine_tick.py"


def scripts_dir() -> Path:
    p = hermes_home() / "scripts"
    p.mkdir(parents=True, exist_ok=True)
    return p


def tick_script_content() -> str:
    plugin_dir = Path(__file__).resolve().parent
    return f'''# Auto-generated by LifeEngine. Do not edit unless you know what you are doing.\nimport os\nimport sys\nfrom pathlib import Path\n\nplugin_dir = Path({str(plugin_dir)!r})\nparent = plugin_dir.parent\nif str(parent) not in sys.path:\n    sys.path.insert(0, str(parent))\n\nfrom lifeengine.runtime import LifeEngineRuntime, format_result\n\nrt = LifeEngineRuntime()\ntry:\n    result = rt.tick(manual=False)\n    # Silent successful ticks keep script-only cron quiet. Print only blocked/errors.\n    if not result.get("ok") or result.get("status") not in {{"ticked", "noop", "done"}}:\n        print(format_result(result))\nfinally:\n    rt.close()\n'''


def write_tick_script() -> Path:
    script_path = scripts_dir() / SCRIPT_NAME
    content = tick_script_content()
    # Avoid rewriting when unchanged so cron script mtime stays stable across
    # repeated health checks and installer runs.
    if not script_path.exists() or script_path.read_text(encoding="utf-8") != content:
        script_path.write_text(content, encoding="utf-8")
    try:
        script_path.chmod(0o755)
    except OSError:
        pass
    return script_path


def cron_create_command(schedule: str = "every 5m", deliver: str = "local", name: str = "lifeengine-heartbeat") -> list[str]:
    return ["hermes", "cron", "create", schedule, "--no-agent", "--script", SCRIPT_NAME, "--deliver", deliver, "--name", name]


def heartbeat_installation_status(schedule: str = "every 5m", deliver: str = "local", name: str = "lifeengine-heartbeat") -> dict[str, Any]:
    script_path = scripts_dir() / SCRIPT_NAME
    expected = tick_script_content()
    exists = script_path.exists()
    current = script_path.read_text(encoding="utf-8") if exists else ""
    return {
        "ok": exists and current == expected,
        "script": str(script_path),
        "script_exists": exists,
        "script_current": exists and current == expected,
        "script_executable": os.access(script_path, os.X_OK) if exists else False,
        "hermes_found": bool(shutil.which("hermes")),
        "command": " ".join(cron_create_command(schedule, deliver, name)),
    }



def _subprocess_env() -> dict[str, str]:
    """Return a clean child env for heartbeat smoke tests.

    Pytest exposes PYTEST_CURRENT_TEST to subprocesses; some host/plugin stacks
    alter behavior when that variable is present.  Cron scripts should run like
    real no-agent cron jobs, so strip pytest-only variables while preserving
    HERMES_HOME and user configuration.
    """
    env = dict(os.environ)
    for key in list(env):
        if key.startswith("PYTEST_"):
            env.pop(key, None)
    return env

def run_tick_script_once(timeout: int = 30) -> dict[str, Any]:
    script = write_tick_script()
    proc = subprocess.run([sys.executable, str(script)], text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=timeout, env=_subprocess_env())
    return {
        "ok": proc.returncode == 0,
        "script": str(script),
        "returncode": proc.returncode,
        "stdout": proc.stdout,
        "stderr": proc.stderr,
    }


def install_heartbeat_cron(schedule: str = "every 5m", deliver: str = "local", name: str = "lifeengine-heartbeat", run_command: bool = False) -> dict[str, Any]:
    script = write_tick_script()
    cmd = cron_create_command(schedule, deliver, name)
    out: dict[str, Any] = {
        "ok": True,
        "script": str(script),
        "command": " ".join(cmd),
        "scheduled": False,
        "status": heartbeat_installation_status(schedule, deliver, name),
    }
    if run_command:
        hermes = shutil.which("hermes")
        if not hermes:
            out.update({"ok": False, "error": "hermes command not found on PATH", "scheduled": False})
            return out
        cmd[0] = hermes
        proc = subprocess.run(cmd, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=30)
        out.update({"scheduled": proc.returncode == 0, "returncode": proc.returncode, "stdout": proc.stdout, "stderr": proc.stderr})
        if proc.returncode != 0:
            out["ok"] = False
    return out


__all__ = [
    "SCRIPT_NAME",
    "scripts_dir",
    "tick_script_content",
    "write_tick_script",
    "heartbeat_installation_status",
    "run_tick_script_once",
    "cron_create_command",
    "install_heartbeat_cron",
]
