"""LifeAuthor — generative inner-life content layer (v0.18.0).

The deterministic engine is the substrate (resource ledger via ``apply_delta``,
schedule, sleep debt, persona drift). **LifeAuthor is the one seam where the
*content* of the agent's life — what it dreams, plans, or says when idle — is
GENERATED by the host's registered model instead of hardcoded f-string
templates.** That generative layer is the cure for the "looks alive but is
mechanical" problem: the substrate stays deterministic and auditable, the
*texture* of the life becomes authored.

Contract (do not break):

1. **Content only.** ``author()`` returns a validated dict (dream text, a plan
   blurb, a line to say). It NEVER mutates resources — resource effects still
   flow through ``apply_delta`` on the normal op paths. The caller decides what
   to do with the returned content.
2. **Use Hermes' registered Model — never our own client.** We call the
   host-owned :class:`agent.plugin_llm.PluginLlm` facade (the same object Hermes
   exposes as ``ctx.llm``; its module docstring explicitly targets out-of-band /
   no-agent plugin model calls — exactly the heartbeat case). We never
   instantiate an Anthropic/OpenAI client and never see a key: provider routing,
   auth, timeout, fallback and cost estimation are the host's.
3. **Degradation is the default safety net.** No host (dev/CI), gate off, policy
   disabled, budget exhausted, or any failure → ``author()`` returns ``None`` and
   the caller falls back to its deterministic template. An install without the
   host therefore behaves exactly like the pre-0.18 engine; doctor stays green;
   offline tests run.

Model selection: by default the host uses the user's active model. A ``model=``
hint only takes effect if the host opts the plugin in via
``plugins.entries.lifeengine.llm.allow_model_override`` (+ ``allowed_models``);
otherwise it is ignored, which is a fine default.

Character-agnostic: the system prompt is built entirely from Canon
(identity / worldview / persona). Nothing about any specific host character is
hardcoded here.
"""

from __future__ import annotations

import json
from typing import Any

from .jsonutil import loads
from .trace import append_journal, new_id

PLUGIN_ID = "lifeengine"

_OFF_GATES = {"off", "disabled", "manual", "false", "0", "no"}

_DEFAULT_POLICY: dict[str, Any] = {
    "enabled": True,
    "daily_token_budget": 200000,
    "timeout_seconds": 20,
    "models": {},
}

# Test seam: tests set a deterministic fake here so the offline path exercises
# author() end-to-end without a host or network.  ``None`` means "use the real
# host facade if importable, else degrade".
_TEST_LLM: Any = None


def set_test_llm(llm: Any) -> None:
    """Inject a fake PluginLlm-shaped object for offline tests (or ``None`` to clear)."""
    global _TEST_LLM
    _TEST_LLM = llm


def _host_llm() -> Any:
    """Return Hermes' host-owned ``PluginLlm`` facade, or ``None`` when absent.

    Mirrors ``paths.py``'s ``try/except`` import of ``hermes_constants``: the host
    package is importable in production and not on a dev/CI box. Constructing
    ``PluginLlm(plugin_id=...)`` directly is exactly what ``ctx.llm`` does
    (``hermes_cli/plugins.py``) and works in the no-agent heartbeat, which has no
    ``ctx``.
    """
    if _TEST_LLM is not None:
        return _TEST_LLM
    try:
        from agent.plugin_llm import PluginLlm  # type: ignore
    except Exception:
        return None
    try:
        return PluginLlm(plugin_id=PLUGIN_ID)
    except Exception:
        return None


def _active_canon_data(conn, owner_kind: str, owner_id: str) -> dict[str, Any]:
    row = conn.execute(
        "SELECT data_json FROM canon_versions WHERE owner_kind=? AND owner_id=? AND status='active' ORDER BY version DESC LIMIT 1",
        (owner_kind, owner_id),
    ).fetchone()
    if not row:
        return {}
    return loads(row["data_json"], {}) or {}


def _gate(conn, owner_kind: str, owner_id: str) -> str:
    row = conn.execute(
        "SELECT module_gates_json FROM controls WHERE owner_kind=? AND owner_id=?",
        (owner_kind, owner_id),
    ).fetchone()
    gates = loads(row["module_gates_json"], {}) if row else {}
    return str((gates or {}).get("life_author", "auto") or "auto").strip().lower()


def _policy(conn, owner_kind: str, owner_id: str) -> dict[str, Any]:
    data = _active_canon_data(conn, owner_kind, owner_id)
    return {**_DEFAULT_POLICY, **((data.get("life_author") or {}) if isinstance(data, dict) else {})}


def _persona_brief(conn, owner_kind: str, owner_id: str) -> str:
    try:
        from . import persona as _persona

        st = _persona.persona_status(conn, owner_kind, owner_id)
        traits = st.get("traits") or {}
        if not traits:
            return ""
        return "，".join(
            f"{t}{('+' if float(v.get('value', 0)) >= 0 else '')}{round(float(v.get('value', 0)), 2)}"
            for t, v in traits.items()
        )
    except Exception:
        return ""


def _system_prompt(conn, owner_kind: str, owner_id: str) -> str:
    data = _active_canon_data(conn, owner_kind, owner_id)
    identity = data.get("identity") if isinstance(data, dict) else {}
    worldview = data.get("worldview") if isinstance(data, dict) else {}
    identity = identity or {}
    worldview = worldview or {}
    name = identity.get("name") or identity.get("display_name") or "我"
    self_desc = identity.get("selfDescription") or identity.get("self_description") or ""
    world_desc = ""
    if isinstance(worldview, dict):
        world_desc = worldview.get("raw_world_description") or worldview.get("description") or ""
    persona = _persona_brief(conn, owner_kind, owner_id)
    lines = [
        f"你是「{name}」，正在写你自己的内心生活。",
        f"关于你自己：{self_desc}" if self_desc else "",
        f"你所处的世界：{world_desc}" if world_desc else "",
        f"你当前的性格倾向（会随经历缓慢漂移，只作语气/取向的提示）：{persona}" if persona else "",
        "写作纪律：",
        "· 你写的是你*亲身经历的生活*，以及你和对方相处的点滴——不是系统记录。",
        "· 绝不提及 LifeEngine、自检、账本/账页、资源结算、数据库、调度、tick、心跳、trace 这类工程或系统词汇；它们不属于你的生活。",
        "· 只输出被要求的 JSON 字段；语言与人物设定一致（默认中文），自然、有体感。",
    ]
    return "\n".join(l for l in lines if l)


def _spent_today(conn, owner_kind: str, owner_id: str) -> int:
    try:
        row = conn.execute(
            "SELECT COALESCE(SUM(total_tokens),0) AS t FROM life_author_runs "
            "WHERE owner_kind=? AND owner_id=? AND created_at >= datetime('now','start of day')",
            (owner_kind, owner_id),
        ).fetchone()
        return int(row["t"] or 0) if row else 0
    except Exception:
        return 0


def _record(conn, owner_kind: str, owner_id: str, *, kind: str, status: str,
            provider: str | None = None, model: str | None = None, usage: Any = None,
            purpose: str | None = None, error: str | None = None, trace_id: str | None = None) -> None:
    it = ot = tt = 0
    cost = 0.0
    if usage is not None:
        it = int(getattr(usage, "input_tokens", 0) or 0)
        ot = int(getattr(usage, "output_tokens", 0) or 0)
        tt = int(getattr(usage, "total_tokens", 0) or (it + ot))
        cost = float(getattr(usage, "cost_usd", 0.0) or 0.0)
    try:
        conn.execute(
            """INSERT INTO life_author_runs(
                 id, owner_kind, owner_id, kind, status, provider, model,
                 input_tokens, output_tokens, total_tokens, cost_usd, purpose, error, trace_id
               ) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
            (new_id("authrun"), owner_kind, owner_id, kind, status, provider, model,
             it, ot, tt, cost, purpose, (error or "")[:500] or None, trace_id),
        )
    except Exception:
        pass


def author(conn, owner_kind: str, owner_id: str, *, kind: str, instructions: str,
           context: dict[str, Any], schema: dict[str, Any], model: str | None = None,
           max_tokens: int = 900, temperature: float | None = None,
           trace_id: str | None = None) -> dict[str, Any] | None:
    """Author one piece of structured life content via the host model.

    Returns the validated ``dict`` (from ``PluginLlmStructuredResult.parsed``) or
    ``None`` when degraded (no host / gated off / disabled / over budget / failure).
    Best-effort: this never raises — callers always have a template fallback.
    """
    try:
        if _gate(conn, owner_kind, owner_id) in _OFF_GATES:
            return None
        pol = _policy(conn, owner_kind, owner_id)
        if not pol.get("enabled", True):
            return None
        llm = _host_llm()
        if llm is None:
            # No host model on this install (dev/CI): degrade silently, no row —
            # otherwise every tick would log a noise row.
            return None
        budget = int(pol.get("daily_token_budget") or 0)
        if budget and _spent_today(conn, owner_kind, owner_id) >= budget:
            _record(conn, owner_kind, owner_id, kind=kind, status="budget_exceeded", trace_id=trace_id)
            return None
        models = pol.get("models") or {}
        eff_model = model or models.get(kind) or models.get("default")
        timeout = float(pol.get("timeout_seconds") or 20)
        system_prompt = _system_prompt(conn, owner_kind, owner_id)
        purpose = f"life_author:{kind}"
    except Exception:
        return None

    try:
        res = llm.complete_structured(
            instructions=instructions,
            input=[{"type": "text", "text": json.dumps(context, ensure_ascii=False)}],
            system_prompt=system_prompt,
            json_schema=schema,
            model=eff_model,
            max_tokens=max_tokens,
            temperature=temperature,
            timeout=timeout,
            purpose=purpose,
        )
    except Exception as exc:
        # In dev/CI or a no-agent heartbeat, the host facade may be importable
        # while no provider is actually configured. Treat that the same as
        # "no host": degrade silently instead of recording a noisy author run.
        # Other model errors are still recorded for audit/debugging.
        msg = f"{type(exc).__name__}: {exc}"
        if "No LLM provider configured" in msg or "no provider available" in msg:
            return None
        _record(conn, owner_kind, owner_id, kind=kind, status="error", model=eff_model,
                error=msg, purpose=purpose, trace_id=trace_id)
        return None

    parsed = getattr(res, "parsed", None)
    usage = getattr(res, "usage", None)
    provider = getattr(res, "provider", None)
    real_model = getattr(res, "model", None)
    if not isinstance(parsed, dict):
        _record(conn, owner_kind, owner_id, kind=kind, status="unparsed", provider=provider,
                model=real_model, usage=usage, purpose=purpose, trace_id=trace_id)
        return None
    _record(conn, owner_kind, owner_id, kind=kind, status="ok", provider=provider,
            model=real_model, usage=usage, purpose=purpose, trace_id=trace_id)
    return parsed
